server:
  port: 8081

spring:
  application:
    name: spring-kafka

  cloud:
    function:
      definition: consumer;producer;
    stream:
      bindings:

        producer-out-0:
          destination: consulta-realizada


        consumer-in-0:
          destination: consulta-realizada

